-- AlterEnum
ALTER TYPE "OtpPurpose" ADD VALUE 'PHONE_VERIFICATION';
ALTER TYPE "OtpPurpose" ADD VALUE 'PHONE_LOGIN';
ALTER TYPE "OtpPurpose" ADD VALUE 'PHONE_PASSWORD_RESET';

-- AlterEnum
ALTER TYPE "SecurityEventType" ADD VALUE 'PHONE_VERIFIED';
ALTER TYPE "SecurityEventType" ADD VALUE 'PHONE_OTP_REQUESTED';
ALTER TYPE "SecurityEventType" ADD VALUE 'PHONE_OTP_RESENT';
ALTER TYPE "SecurityEventType" ADD VALUE 'PHONE_LOGIN_SUCCESS';
ALTER TYPE "SecurityEventType" ADD VALUE 'PHONE_LOGIN_FAILURE';
ALTER TYPE "SecurityEventType" ADD VALUE 'PHONE_PASSWORD_RESET_REQUESTED';
ALTER TYPE "SecurityEventType" ADD VALUE 'PHONE_PASSWORD_RESET_SUCCESS';
ALTER TYPE "SecurityEventType" ADD VALUE 'PHONE_NUMBER_CHANGED';
ALTER TYPE "SecurityEventType" ADD VALUE 'SMS_DELIVERY_FAILED';

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "passwordHash" DROP NOT NULL,
ADD COLUMN "phoneNumber" TEXT,
ADD COLUMN "phoneNumberVerifiedAt" TIMESTAMP(3);

-- CreateIndex
CREATE UNIQUE INDEX "User_phoneNumber_key" ON "User"("phoneNumber");

-- CreateIndex
CREATE INDEX "User_phoneNumber_idx" ON "User"("phoneNumber");
